### ISSUE TITLE
Not able to install new version

### ISSUE THREAD

**Issue by cfvo** [BlythMeister/Gallifrey#126]
Installation note: 
FEILOPPLYSNINGER
	Følgende feil ble påvist under denne operasjonen.
	* [15.05.2015 12:55:21] System.Runtime.InteropServices.COMException
		- Dataformatet for programbinding er ugyldig. (Exception from HRESULT: 0x800736B2)
		- Kilde: System.Deployment
		- Stakksporing:
			ved System.Deployment.Internal.Isolation.IEnumSTORE_ASSEMBLY.Next(UInt32 celt, STORE_ASSEMBLY[] rgelt)
			ved System.Deployment.Internal.Isolation.StoreAssemblyEnumeration.MoveNext()
			ved System.Deployment.Application.ComponentStore.CollectCrossGroupApplications(Uri codebaseUri, DefinitionIdentity deploymentIdentity, Boolean& identityGroupFound, Boolean& locationGroupFound, String& identityGroupProductName)
			ved System.Deployment.Application.SubscriptionStore.CommitApplication(SubscriptionState& subState, CommitApplicationParams commitParams)
			ved System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			ved System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			ved System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

TRANSAKSJONSDETALJER FOR KOMPONENTLAGER
	Transaksjonsinformasjon er ikke tilgjengelig.

**Comment by BlythMeister** [comment]
English Translation:

INCORRECT INFORMATION
The following errors were detected during this operation.
* [15/05/2015 12:55:21] System.Runtime.InteropServices.COMException
- The data format for application binding is invalid. (Exception from HRESULT: 0x800736B2)
- Source: System.Deployment
- Stack trace:
by System.Deployment.Internal.Isolation.IEnumSTORE_ASSEMBLY.Next (uint32 Celt, STORE_ASSEMBLY [] rgelt)
by System.Deployment.Internal.Isolation.StoreAssemblyEnumeration.MoveNext ()
by System.Deployment.Application.ComponentStore.CollectCrossGroupApplications (Uri codebaseUri, DefinitionIdentity deploymentIdentity, Boolean & identity group found, Boolean & location group found, String & identity group product name)
by System.Deployment.Application.SubscriptionStore.CommitApplication (SubscriptionState & sub-state, CommitApplicationParams commitParams)
by System.Deployment.Application.ApplicationActivator.InstallApplication (SubscriptionState & sub-state, ActivationDescription actDesc)
by System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation (Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, Browser Settings browser settings, String & errorPageUrl)
by System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker (Object state)

TRANSACTION DETAILS OF COMPONENT STOCK
Transaction information is not available.

**Comment by BlythMeister** [comment]
looking at the trace, this doesn't show any Gallifrey code.

Can you please tell me the operating system & url the installer was downloaded from?

**Comment by cfvo** [comment]
Hi,
I’m running Window 7 and the url used for download is http://blythmeister.github.io/Gallifrey.Releases/deploy/stable/setup.exe.

\CF

**Comment by BlythMeister** [comment]
The only time i have seen install fail is due to our company group policy.

Can you have a look in the event viewer for an error around when the you installed.

If not, i'm not really sure what else to suggest.

**Comment by cfvo** [comment]
After searching the internet for similar problem I finally solved the issue. I needed to delete a manifest for a previous version of Gallifrey under Users\[username]\AppData\Local\Apps\2.0\JH0D3Y78.GB8\H2ZRHK72.3K6\manifests\

**Comment by BlythMeister** [comment]
Great good to have a solution. 
Microsoft Click-Once installs can be a pain, I've looked at other methods, but they also have issues. 
I'll close this one down, thanks for letting me know you sorted it.
