### ISSUE TITLE
New UI - Bulk export grid/matrix

### ISSUE THREAD

**Issue by richard-green** [BlythMeister/Gallifrey#141]
Hi,

This might be nice to be able to export selected time that's ready, with a grid allowing you to pre-configure all the info such as comments / remaining time, then when ready export all.

This would then show the progress of each export in turn and you can watch it trundle through the list and/or retry failed attempts

Thanks,
Richard

**Comment by BlythMeister** [comment]
Implemented this. 
Handling failures is tough, so a failure will alert you and halt progress.
Upgrading progress also tough with the way the progress dialog works, but you get a message saying it's doing stuff.
