### ISSUE TITLE
Suggestion: Let me add a comment on Timer creation \ Edit

### ISSUE THREAD

**Issue by Dave-Thompson-15below** [BlythMeister/Gallifrey#174]
When I create or edit a timer allow me to add a comment that will be added when I export it to Jira.
![gallifrey comment to timer](https://cloud.githubusercontent.com/assets/1055807/13226036/717ee29e-d987-11e5-8402-50f143d16169.PNG)

**Comment by BlythMeister** [comment]
You can turn on a prompt so when you add a timer with time it offers the export of that time. 
A timer can reflect a jira with many different meanings like "meetings" so having a comment on add means the comment will need to change.

That is why the prompts exist to help with that sort of jira.

Does that function help/solve the issue your having?

**Comment by Dave-Thompson-15below** [comment]
Thanks Chris. This definitely helps.
Would be nice to be able to add comment as you add time and then these times/comments are added then as a batch when you choose to export.
Cheers.

**Comment by BlythMeister** [comment]
i agree it would be nice, but gallifrey has always been designed as a single timer model and not designed for bucket type jiras which need that level of granular exporting.
I've put work arounds in place, but without a significant change to the way Gallifrey works, this isn't going to be possible.
