### ISSUE TITLE
Better UX for the "Time Spinners"

### ISSUE THREAD

**Issue by richard-green** [BlythMeister/Gallifrey#182]
### Overview

When editing a Timer, the spinners for the "current time" field can be a bit clunky.
Firstly, incrementing by single minutes is not particularly useful, perhaps consider increments of 5/10/15 minutes (bonus points for it being configurable!)
Secondly, would be awesome if incrementing minutes would roll over an additional hour if it went to 60!

### Expected Behavior

Either clicking the +/- buttons or pressing the up/down keyboard arrows results in different increment sizes for the minutes field
Incrementing minutes past 59 will roll it back to zero and increment hours by 1
Decrementing minutes past 0 will loop it round to 59 and decrement hours by 1 (if not at zero already, in which case stop hard at zero)

--
### System Info

Gallifrey Version: _v3.1.0_
Operating System Version: _Win 7_
Jira Cloud/Self Host: _Cloud_
Jira Version: _?_

**Comment by BlythMeister** [comment]
feature added...no bonus points though.
Increments of 5.
Added a few other nice things like entering selects text & fixing the dodgy error message
