### ISSUE TITLE
Order issues using a filter on search

### ISSUE THREAD

**Issue by luissmg** [BlythMeister/Gallifrey#190]
### Overview

When you have a filter on JIRA and you apply that filter on Gallifrey (issue search) does not respect the order parameter.

### Expected Behavior

When you save a filter and you specify the "Order by", i.e. ordering by the rank of an issue inside a sprint, it should apply the order condition on gallifrey

### Actual Behavior

When you have a filter on JIRA and you apply that filter on Gallifrey it always orders by the id/name of the issue (I think).

### Steps To Reproduce Behavior

Add a filter on JIRA, filter by a sprint and by rank (ASC or DESC). Test the filter on Gallifrey.

--
### System Info

Gallifrey Version: 3.2.1.0
Operating System Version: Windows 8
Jira Version: 7.0.2

**Comment by BlythMeister** [comment]
Fix applied, will be in next deployment of beta and in the next stable.
