### ISSUE TITLE
Use both search term and search filter in "Search Jira"

### ISSUE THREAD

**Issue by luissmg** [BlythMeister/Gallifrey#197]
### Overview

While searching for issues in Gallifrey, apply a search filter and a term filter.

### Expected Behavior

In the "Search Jira", use the search filter to get a small list of issues and then use the term filter to find the issue.
This can be helpful if I have the same name for more than one issue. I can apply a search filter to get the issues of my active sprint and then find the issue inside it.

### Actual Behavior

Gallifrey allows you to search for a term OR using a filter.

### Steps To Reproduce Behavior

Open the "Search Jira". It should appear a search term and a search filter. We can't use both at the same time.

--
### System Info

Gallifrey Version: 3.2.1.0
Operating System Version: Windows 8
Jira Version: 7.0.2

**Comment by BlythMeister** [comment]
Hi,

This would be possible but basically means running 2 queries.

1) search term
2) filter

then intersecting the results in order to find the jiras that appear in both record sets.

I will investigate how this works, but like is as an idea, never thought of it before!

**Comment by luissmg** [comment]
I was thinking if it was possible to get the query of the filter and then add the query of the term.
This way you have only one query running. But I don't know if that is possible

**Comment by BlythMeister** [comment]
technically, parsing the JQL in the filter is doable, but i would need to cater for all the different formats of the JQL including ordering.
I have implemented to dual search, and it seems to work quite nicely from my limited testing
feel free to install the beta and try it out :)

**Comment by luissmg** [comment]
I'm going to install your beta version and try it out tomorrow. I will give you some feedback about this

**Comment by luissmg** [comment]
I have already tested it. I used an advanced search to test it. Here it is:
**project = Project Name AND status in ("In Progress", "To Do") AND sprint in openSprints() AND sprint not in futureSprints() ORDER BY cf[10009] ASC**

Then I applied the term search. I must say it worked perfectly :)
I'm closing the issue as it is already implemented and tested.
