### ISSUE TITLE
Change issue status on export

### ISSUE THREAD

**Issue by luissmg** [BlythMeister/Gallifrey#201]
### Overview

Change the status of an issue when you export is timer

### Expected Behavior

When you create a timer, it gives you the option to change the status of the issue.
My idea is to do the same when you export a timer. You could change the issue to "Done" if it fits you.
If implemented, this would be a premium functionality.

### Actual Behavior

It's a new functionality.

### Steps To Reproduce Behavior

It's a new functionality.

--
### System Info

Gallifrey Version: 3.2.1.0
Operating System Version: Windows 8
Jira Version: 7.0.2

**Comment by BlythMeister** [comment]
Now part of the beta for 3.3.1
