### ISSUE TITLE
Default Jiras

### ISSUE THREAD

**Issue by mrshauneeb** [BlythMeister/Gallifrey#204]
### Overview

Possible feature idea - Add the ability to set default jiras that are already added with 0 time when a new  working day begins. For daily tasks. 

### Expected Behavior

When a new working day begins and is added, add the default jiras to it with 0:00 time.
Would need some way of specifying which jiras are defaults.

### Actual Behavior

n/a

### Steps To Reproduce Behavior

n/a

--
### System Info

n/a

**Comment by BlythMeister** [comment]
Should these only be added for working days?

**Comment by luissmg** [comment]
@BlythMeister I think yes. I don't think you should have in consideration the days that you are not supposed to work

**Comment by luissmg** [comment]
I think the idea is good. It can be practical. But if every day you change the issues you are working and you need to set them up every single day I would not use this.

I think that what can be done with this is to see if the tasks from the day before are done. If not, add them the way you said @mrshauneeb 

What you think?
