### ISSUE TITLE
Lock timers as on optional feature (bonus: timer thresholds)

### ISSUE THREAD

**Issue by richard-green** [BlythMeister/Gallifrey#205]
### Overview

The lock timers, while useful, can seem a bit demanding when you have hundreds of 1-2 minute locks (making tea!), so it would be nice to either disable them or potentially have a threshold of (e.g.) 5 minutes before which they are simply discarded

### Expected Behavior

If I set them to disabled, I don't want to record lock timers or be shown the lock timer flyout on login.
If I set them to a threshold of 5 minutes, I don't want to record timers below that threshold and only show the flyout if a new "longer-than-5-minutes" timer was just added.

**Comment by BlythMeister** [comment]
Both doable :)
Watch this space!
