### ISSUE TITLE
Right click shows the wrong menu

### ISSUE THREAD

**Issue by luissmg** [BlythMeister/Gallifrey#206]
### Overview

When I have no timers running and I right click in gallifrey it shows the timer's menu and not the context menu.

### Expected Behavior

It should open the context menu so I can add a new timer.

### Actual Behavior

The app show the timer menu instead of the context menu when you right click outside an issue.

### Steps To Reproduce Behavior

Right click outside a timer and it will show the wrong menu.

--
### System Info

Gallifrey Version: 3.3.0.0
Operating System Version: Windows 8
Jira Version: 7.0.2

**Comment by BlythMeister** [comment]
This was changed for this version to behave like this.
Right click on the date shows the menu you are expecting.

The reason for this is that is you managed to click between timers, you got the wrong menu.

I'll see if i can make it work nicer so right click in space gives the add menu, but right click on timer gives timer menu.

**Comment by luissmg** [comment]
Hmmm I understand your concern. But if I click between the timers I'm not clicking in any timer so the behaviour was right in my opinion

I saw the change log but I really thought it was a bug. Anyway good job on the improvements!
