### ISSUE TITLE
Local Times should not be marked for Export

### ISSUE THREAD

**Issue by LouAlicegary** [BlythMeister/Gallifrey#208]
### Overview

Since local timers should not export to Jira, they should not have "XX:XX to export" marked and they should not be included in the "Unexported time" calculation at the bottom of the window.

### Expected Behavior

Local timers should be treated differently than time for export.

### Actual Behavior

See overview.

### Steps To Reproduce Behavior

1) Create a new Local timer.
2) Stop the timers.
3) Note that the timer says "XX:XX To Export"
4) Note that the local timer is included in the "Unexported Time" calculation at the bottom of the window.

--
### System Info

Gallifrey Version: v3.3.1.0
Operating System Version: Windows 7
Jira Cloud/Self Host: Cloud
Jira Version: v1000.482.3

**Comment by BlythMeister** [comment]
Great spot! 
I don't use local timers often so never noticed. 

Will take a look into this, shouldn't be too tricky to fix.

**Comment by BlythMeister** [comment]
Update as part of next version (released to beta already) now shows:

![image](https://cloud.githubusercontent.com/assets/1046836/19960046/59f4a486-a1a2-11e6-9698-f6540cf9f80d.png)

Whereby unexported does not include local time, but local time is still displayed seperately
