### ISSUE TITLE
Max Time On Edit

### ISSUE THREAD

**Issue by BlythMeister** [BlythMeister/Gallifrey#217]
### Overview

When a timer goes above 9:59 and you try to edit it the hours will hit the maximum of 9 and lock there.

### Expected Behavior

Timer shouldn't tick above 9:59

### Actual Behavior

Time ticks above. but export and edit doesn't allow time to be used

### Steps To Reproduce Behavior

Create a timer with 9:58.
Start it
Wait 2 minutes
Timer gets to 10:00

**Comment by mrshauneeb** [comment]
Set edit to have max of 23 hours instead of stopping timers running 👍
