### ISSUE TITLE
Lost timers after updating

### ISSUE THREAD

**Issue by andrew-armitage-15below** [BlythMeister/Gallifrey#263]
**Describe the bug**
When updating Gallifrey I clicked the apply update button multiple times which opened more than one instance. The result of this was that I lost all un-exported and temp work logs.

**To Reproduce**
1. When an update has been downloaded and needs to be installed click apply update button multiple times

**Expected behavior**
1. Gallifrey is opened and existing work logs are present

**Comment by BlythMeister** [comment]
I'm not sure if the update is a crucial part here.

I think the issue is around multiple instances and the saving of the data files.

I will work on a better way to handle that use case which should solve the issue.

**Comment by BlythMeister** [comment]
Have updated the way backups work to give 24 rolling backups.
Each new backup is created when the previous one is over an hour old.
