### ISSUE TITLE
Pause timers if Pc is in Idle (i.e keyboard or mouse not being used) like in PC locked state

### ISSUE THREAD

**Issue by Voize** [BlythMeister/Gallifrey#92]
Pause timers if Pc is in Idle (i.e keyboard or mouse not being used) like in PC locked state was not sure if this was a feature which was present or something in the works for a future release

**Comment by BlythMeister** [comment]
One more specific to wpf. 
http://weblogs.asp.net/jdanforth/detecting-idle-time-with-global-mouse-and-keyboard-hooks-in-wpf
Like the idea, want to put in really...

**Comment by BlythMeister** [comment]
Going to have another crack at this one!
this may be of use: http://stackoverflow.com/questions/4963135/wpf-inactivity-and-activity
